import {Muxer,ArrayBufferTarget} from 'https://esm.sh/mp4-muxer@5.2.2';
const $=s=>document.querySelector(s);const filesEl=$('#files'),logoEl=$('#logo'),ratioEl=$('#ratio'),durationEl=$('#duration'),canvas=$('#canvas'),ctx=canvas.getContext('2d',{alpha:false}),statusEl=$('#status'),empty=$('#empty'),thumbs=$('#thumbs'),downloadEl=$('#download');
let images=[],logo=null,rendering=false,downloadUrl=null;
const RATIOS={'9:16':[9,16],'4:5':[4,5],'1:1':[1,1],'16:9':[16,9]};
function setStatus(t){statusEl.textContent=t}
function fitSize(ratio){const [rw,rh]=RATIOS[ratio],maxW=900,maxH=1200;let w=maxW,h=w*rh/rw;if(h>maxH){h=maxH;w=h*rw/rh}canvas.width=Math.round(w/2)*2;canvas.height=Math.round(h/2)*2}
function loadImage(file){return new Promise((res,rej)=>{const u=URL.createObjectURL(file),im=new Image();im.onload=()=>{URL.revokeObjectURL(u);res(im)};im.onerror=rej;im.src=u})}
function drawCover(im,alpha=1,scale=1,x=0,y=0,blur=0){ctx.save();ctx.globalAlpha=alpha;ctx.filter=blur?`blur(${blur}px)`:'';const s=Math.max(canvas.width/im.width,canvas.height/im.height)*scale,w=im.width*s,h=im.height*s;ctx.drawImage(im,(canvas.width-w)/2+x,(canvas.height-h)/2+y,w,h);ctx.restore()}
function containRect(im,scale=1){const s=Math.min(canvas.width/im.width,canvas.height/im.height)*scale;return {w:im.width*s,h:im.height*s,x:(canvas.width-im.width*s)/2,y:(canvas.height-im.height*s)/2}}
function drawFrame(t){const n=images.length;if(!n)return;const total=Number(durationEl.value)*1000,tt=((t%total)+total)%total,seg=total/n,i=Math.min(n-1,Math.floor(tt/seg)),p=(tt-i*seg)/seg,next=(i+1)%n;ctx.clearRect(0,0,canvas.width,canvas.height);const im=images[i],im2=images[next];drawCover(im,1,1.08,0,0,18);if(p>.82)drawCover(im2,(p-.82)/.18,1.08,0,0,18);const panX=Math.sin(t/850+i*1.7)*canvas.width*.035,panY=Math.cos(t/1050+i)*canvas.height*.028;const r=containRect(im,.94);ctx.save();ctx.globalAlpha=p>.82?1-(p-.82)/.18:1;ctx.translate(panX,panY);ctx.drawImage(im,r.x,r.y,r.w,r.h);ctx.restore();if(p>.82){const r2=containRect(im2,.94);ctx.save();ctx.globalAlpha=(p-.82)/.18;ctx.translate(-panX*.55,-panY*.55);ctx.drawImage(im2,r2.x,r2.y,r2.w,r2.h);ctx.restore()}drawMovingImages(t);if(logo)drawLogo(t)}
function drawMovingImages(t){if(images.length<2)return;const band=Math.max(64,canvas.height*.13),speed=canvas.width*.16,offset=(t/1000*speed)%(canvas.width+band*2);ctx.save();ctx.globalAlpha=.94;const count=Math.max(4,Math.ceil(canvas.width/(band*1.25))+2);for(let row=0;row<2;row++){const y=row?canvas.height-band:0;for(let k=-1;k<count;k++){const idx=(k+Math.floor(t/2400)+row+images.length*10)%images.length,im=images[idx],w=band*1.05*im.width/im.height,x=k*band*1.25-(offset*(row?-.65:1));ctx.drawImage(im,x,y,w,band)}}ctx.restore()}
function drawLogo(t){const size=Math.min(canvas.width,canvas.height)*.09;ctx.save();ctx.translate(canvas.width-size*.7,canvas.height-size*.7);ctx.rotate(t/900);ctx.beginPath();ctx.arc(0,0,size/2,0,Math.PI*2);ctx.clip();ctx.drawImage(logo,-size/2,-size/2,size,size);ctx.restore()}
function updateThumbs(){thumbs.innerHTML='';images.forEach(im=>{const c=document.createElement('canvas');c.width=70;c.height=86;const x=c.getContext('2d'),s=Math.min(70/im.width,86/im.height);x.drawImage(im,(70-im.width*s)/2,(86-im.height*s)/2,im.width*s,im.height*s);const img=document.createElement('img');img.src=c.toDataURL();thumbs.append(img)})}
async function chooseImages(list){const chosen=[...list].filter(f=>f.type.startsWith('image/')).slice(0,5);if(!chosen.length)return;clearResult(false);images=await Promise.all(chosen.map(loadImage));fitSize(ratioEl.value);empty.style.display='none';updateThumbs();drawFrame(0);setStatus(`${images.length} gambar siap. Preview lokal aktif.`)}
filesEl.onchange=e=>chooseImages(e.target.files);$('#drop').ondragover=e=>{e.preventDefault()};$('#drop').ondrop=e=>{e.preventDefault();chooseImages(e.dataTransfer.files)};ratioEl.onchange=()=>{fitSize(ratioEl.value);drawFrame(0)};logoEl.onchange=async e=>{logo=e.target.files[0]?await loadImage(e.target.files[0]):null;drawFrame(0)};$('#clearLogo').onclick=()=>{logo=null;logoEl.value='';drawFrame(0)};
let raf=0;function preview(){if(!images.length){setStatus('Tambahkan minimal 1 gambar.');return}cancelAnimationFrame(raf);const start=performance.now();const loop=now=>{drawFrame(now-start);raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);setStatus('Preview berjalan…')}
$('#preview').onclick=preview;
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function clearResult(resetImages=true){if(downloadUrl){URL.revokeObjectURL(downloadUrl);downloadUrl=null}downloadEl.hidden=true;downloadEl.removeAttribute('href');downloadEl.removeAttribute('download');if(resetImages){images=[];logo=null;filesEl.value='';logoEl.value='';thumbs.innerHTML='';empty.style.display='block';ctx.clearRect(0,0,canvas.width,canvas.height)}}
downloadEl.onclick=()=>{if(!downloadUrl)return;setTimeout(()=>{clearResult(true);setStatus('Download selesai. Gambar dan MP4 sementara sudah dihapus dari browser. Tambahkan gambar baru untuk membuat video lagi.')},1200)};
async function renderMp4(){if(rendering)return;if(!images.length){setStatus('Tambahkan minimal 1 gambar.');return}rendering=true;cancelAnimationFrame(raf);fitSize(ratioEl.value);const fps=30,totalFrames=Math.round(Number(durationEl.value)*fps),target=new ArrayBufferTarget(),muxer=new Muxer({target,video:{codec:'avc',width:canvas.width,height:canvas.height,frameRate:fps},fastStart:'in-memory'});let failed=null;const encoder=new VideoEncoder({output:(chunk,meta)=>muxer.addVideoChunk(chunk,meta),error:e=>{failed=e}});encoder.configure({codec:'avc1.4d401f',width:canvas.width,height:canvas.height,bitrate:Math.min(9000000,Math.max(2500000,canvas.width*canvas.height*5)),framerate:fps});try{for(let f=0;f<totalFrames;f++){drawFrame(f*1000/fps);const frame=new VideoFrame(canvas,{timestamp:Math.round(f*1e6/fps),duration:Math.round(1e6/fps)});encoder.encode(frame,{keyFrame:f%60===0});frame.close();if(f%10===0){setStatus(`Rendering ${Math.round(f/totalFrames*100)}%`);await sleep(0)}}await encoder.flush();if(failed)throw failed;muxer.finalize();const blob=new Blob([target.buffer],{type:'video/mp4'});downloadUrl=URL.createObjectURL(blob);downloadEl.href=downloadUrl;downloadEl.download=`iwan-image-to-video-${ratioEl.value.replace(':','x')}-${durationEl.value}s.mp4`;downloadEl.hidden=false;setStatus(`Selesai. MP4 ${Math.round(blob.size/1024/1024*10)/10} MB siap. Tekan Download MP4.`)}catch(e){console.error(e);setStatus(`Render gagal: ${e.message||e}. Gunakan Chrome/Edge terbaru.`)}finally{encoder.close();rendering=false}}
$('#render').onclick=renderMp4;setStatus('Siap. Semua proses dilakukan di browser.');